general {
	lock_cmd = qs -c /home/zeamanuel/.config/quickshell/angular-frame/widgets/LockScreen/
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
  timeout = 300
  on-timeout = loginctl lock-session
}

listener {
  timeout = 480
  on-timeout = brightnessctl -s set 0
  on-resume = brightnessctl -r
}

listener {
  timeout = 480
  on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
  on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}

listener {
  timeout = 900
  on-timeout = systemctl suspend
}
